FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
	curl \
	build-essential \
	dumb-init \
	git \
	htop \
	less \
	locales \
	nano \
	net-tools \
	openssl \
	software-properties-common \
	sudo \
	unzip \
	vim \
	wget \
	&& rm -rf /var/lib/apt/lists/*